  train_data: "datasets/annotations/train_dataset.txt"
  val_data: "datasets/annotations/val_dataset.txt"

  batch_size: 2
  model_path: ''

  lr: 0.0001
  num_epoch: 100

  model_layers: [3, 4, 6, 3]